services:
  postgresql:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data: