quarkus.application.name=kubeoptix-configurations
quarkus.http.port=8000
quarkus.http.host=0.0.0.0

quarkus.smallrye-openapi.info-title=KubeOptix Configurations API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API for KubeOptix system settings.
quarkus.swagger-ui.always-include=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRESQL_USER}
quarkus.datasource.password=${POSTGRESQL_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL_HOST:kubeoptix-db}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE}
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE}
quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=true
%dev.quarkus.hibernate-orm.log.bind-parameters=true
