replicaCount: 1

image:
  repository: quay.io/parraes/kubeoptix-configurations
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  name: configurations-api
  type: ClusterIP
  port: 8000

containerPort: 8000

buildConfig:
  enabled: true
  gitUri: https://github.com/ShiftWise-AI/kubeoptix-configurations.git
  gitRef: main
  sourceSecret:
    enabled: true
    name: github-auth
