{{- if not .Values.postgresql.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeoptix-postgresql.secretName" . }}
  labels:
    {{- include "kubeoptix-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.secretKeys.username }}: {{ .Values.postgresql.username | quote }}
  {{ .Values.postgresql.secretKeys.password }}: {{ .Values.postgresql.password | quote }}
  {{ .Values.postgresql.secretKeys.database }}: {{ .Values.postgresql.database | quote }}
{{- end }}
