apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeoptix-postgresql.fullname" . }}
  labels:
    {{- include "kubeoptix-postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "kubeoptix-postgresql.selectorLabels" . | nindent 4 }}
